modLoader="kotlinforforge"
# Change this if you require a certain version of KotlinForForge
loaderVersion="[3,)"
license = "GNU GPLv3"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]] #mandatory
modId = "cccc"
version = "${file.jarVersion}" #mandatory
displayName = "Create: Contextual Cogs n Chains" #mandatory TODO: change this!
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="createaddon.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
#authors = "You" #optional
# The description text for the mod (multi line!) (#mandatory) TODO: change this!
description = '''
Your Create addon description!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
# TODO: change all of the depdendencies.cccc to dependencies.(your modid) !
[[dependencies.cccc]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[40.2,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
# Here's another dependency
[[dependencies.cccc]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.cccc]]
modId = "create"
mandatory = true
versionRange = "[0.5.1)"
ordering = "AFTER"
side = "BOTH"
